# name, on, jobs are mandantory
# One file
# 'My second github action'
name: 'My first github action'

# event name
on: [ 'push', 'pull_request' ]

# workflow
jobs:
  first-job:
    name: 'first job'

    runs-on: ubuntu-latest

    steps:
    - name: output value 1
      id: first
      shell: bash
      run: |
        echo "Hello, world!"

    - name: output value 2
      id: first
      if: github.event_name == 'pull_request'
      shell: bash
      run: |
        echo "Hello, world!"

  second-job:
    name: 'second job'
    if: github.event_name == 'pull_request'

    runs-on: ubuntu-latest

    steps:
    - name: output value
      id: first
      shell: bash
      run: |
        echo "Hello, world!"
