# name, on, jobs are mandantory
# One file
# 'My second github action'
name: 'My first github action'

# when
on: push

# workflow
jobs:
  first-job:
    name: 'first job'

    strategy:
      matrix:
        os: [ 'windows-latest', 'macos-latest', 'ubuntu-latest']
        nodejs: [ '14.x', '16.x' ]

    # build server
    runs-on: ${{ matrix.os }}

    steps:
    - name: Setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.nodejs }}

    - name: output value from ${{ matrix.os }}
      id: first
      shell: bash
      run: |
        echo "OS: ${{ matrix.os }}"
        echo "node.js: ${{ matrix.nodejs }}"
