# name, on, jobs are mandantory
# One file
# 'My second github action'
name: 'My first github action'

# when
on: push

# workflow
jobs:
  first-job:
    name: 'first job'

    # build server
    runs-on: ubuntu-latest

    # job level environment
    env:
      JOB_LEVEL_1: 'This comes from job level 1'

    steps:
    - name: Say Hello World 1
      shell: bash
      env:
        STEP_LEVEL_1: 'This comes from step level 1'
      #
      run: |
        echo "Hello World from step 1"
        echo "STEP_VALUE_1='THIS IS SET BY STEP 1'" >> $GITHUB_ENV

    - name: Say Hello World 2
      shell: pwsh
      # github env : json 형태
      # 두 번째 세 번째는 pwsh에서 가져올때 해당
      run: |
        echo "Hello World from step 2"
        echo "VALUE: $env:STEP_VALUE_1"
        echo "VALUE: ${{ env.STEP_VALUE_1 }}"

    - name: Say Hello World 3
      shell: bash
      run: |
        echo "Hello World from step 2"
        echo "VALUE: $STEP_VALUE_1"
        echo "VALUE: ${{ env.STEP_VALUE_1 }}"
