# name, on, jobs are mandantory
# One file
# 'My second github action'
name: 'My first github action'

# when
on: push

# workflow
jobs:
  first-job:
    name: 'first job'

    # build server
    runs-on: ubuntu-latest

    # job level environment
    env:
      JOB_LEVEL_1: 'This comes from job level 1'

    steps:
    - name: mask value
      id: first
      shell: bash
      # assing $first_value to my_first_value
      # output might be secure than env
      run: |
        first_value="This is the first output value"

        echo "::add-mask::$first_value"
        echo "::set-output name=my_first_value::$first_value"

    - name: get output value
      shell: bash
      # ${{}} -> github action grammer
      run: |
        echo ${{ steps.first.outputs.my_first_value }}
