# name, on, jobs are mandantory
# One file
# 'My second github action'
name: 'My first github action'

# event name
# can specify event condition to job or steps
on: [ 'push', 'pull_request' ]

# workflow
jobs:
  first-job:
    name: 'first job'

    runs-on: ubuntu-latest

    steps:
    - name: output value 1
      shell: bash
      run: |
        echo "Hello, world!"

    - name: output value 2
      shell: bash
      run: |
        echo "Hello, world!"

  second-job:
    name: 'second job'
    needs: first-job

    runs-on: ubuntu-latest

    steps:
    - name: output value
      shell: bash
      run: |
        echo "Hello, world!"

  third-job:
    name: 'third job'
    needs: second-job

    runs-on: ubuntu-latest

    steps:
    - name: output value
      shell: bash
      run: |
        echo "Hello, world!"
